# Generated by Django 4.2.7 on 2023-11-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('notes', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='contact_Details',
        ),
    ]
