# Generated by Django 4.2.7 on 2023-11-29 04:47

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact_management', '0002_contactsinfo_delete_contact_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsinfo',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contactsinfo',
            name='email',
            field=models.EmailField(default=datetime.datetime(2023, 11, 29, 4, 47, 35, 574311, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
